### ISSUE TITLE
Visualizer not working properly

### ISSUE THREAD

**Issue by GreatRash** [JexCheng/regulex#20]
I think this expression - http://jex.im/regulex/#!embed=false&flags=&re=%5Ea%7Cb%24
and this expression - http://jex.im/regulex/#!embed=false&flags=&re=%5E(a%7Cb)%24
should look the same, except of 'group' block

**Comment by JexCheng** [comment]
It shouldn't:
```javascript
/^a|b$/.test("ac")
// => true
/^a|b$/.test("cb")
// => true

/^(a|b)$/.test("ac")
// =>false
/^(a|b)$/.test("a")
```
