### ISSUE TITLE
Support Named Capture Groups

### ISSUE THREAD

**Issue by w3ttr3y** [JexCheng/regulex#22]
It would be great if you could support named capture groups e.g. (?<foo>.*)

Even if initially you just did a search replace removing them, it would make it much easier to copy and paste a regex in to visualize as I just manually removed 10 from a regex I copied in to check out your tool.

Long term, it would be great to add them to the visualization as a label, but I can respect that its more work and I'm asking for something without giving anything back.

**Comment by JexCheng** [comment]
It will be realized in #16  PCRE milestone (in the future :snail:  )

**Comment by liudongmiao** [comment]
demo: jianyu.io/regulex/
