### ISSUE TITLE
zero-width assertions not supported

### ISSUE THREAD

**Issue by ahxxm** [JexCheng/regulex#23]
regex like this: (?<=abc>[\s\S]*?(?=def)

**Comment by JexCheng** [comment]
https://github.com/JexCheng/regulex/issues/16

PCRE milestone

**Comment by liudongmiao** [comment]
should be `(?<=abc)[\s\S]*?(?=def)`

**Comment by liudongmiao** [comment]
demo: jianyu.io/regulex/
