### ISSUE TITLE
is there a way to support python style named groups easily with the parser you have?

### ISSUE THREAD

**Issue by dkoshe** [JexCheng/regulex#25]
I want to display the regex graphically, but that comes from our python backend.
Currently the parser chokes on syntax like (?P<name> 
How do I change so that group is recognized with (?P and name <>) ?
thanks for your help.

**Comment by JexCheng** [comment]
In progress  PCRE: https://github.com/JexCheng/regulex/issues/16

**Comment by liudongmiao** [comment]
demo: jianyu.io/regulex/
