### ISSUE TITLE
Improve error message for repeat after group or assertion case.

### ISSUE THREAD

**Issue by JexCheng** [JexCheng/regulex#29]
Give a tip for `([a-z]){3}`,Repeat after capture group, only the last appearance will be captured. For example: `/([a-z]){3}/.exec("abc")` will result  ` ["abc","c"]`

`/a(?=bc){3}/`、`/a(?=bc)+/`  should warn "They are the same as `/a(?=bc)/`"
`/a(?=bc)*/`、 `/a(?=bc){0,3}/`、 `/a(?=bc)?/` should warn "They are the same as `/a/` "

**Comment by RReverser** [comment]
> And `/a(?=bc)?/` should not warn.

Why not  btw? What's the effect of it?

**Comment by JexCheng** [comment]
@RReverser 
 I think maybe I need to make a distinction between error and warning. 

You're right,(and I was right, last night I'm confused and forgot this :wine_glass:  :sleeping:  :laughing:  ), It should warn explicitly  `/a(?=bc)?/` is same as `/a/`.
