### ISSUE TITLE
I can't export image

### ISSUE THREAD

**Issue by zhangsenhua** [JexCheng/regulex#36]
I write a regular expression，I would download the corresponding visual image, but I can't do it.
Error:
Mixed Content: The page at 'https://jex.im/regulex/#!embed=false&flags=&re=%5E%23-%3F%5B1-9%5D%2B%5B0-9%5D*%3A-%3F(%5B0-9%5D%7C%5B1-9%5D%2B%5B0-9%5D*)%24' was loaded over HTTPS, but requested an insecure script 'http://libs.useso.com/js/require.js/2.1.11/require.min.js'. This request has been blocked; the content must be served over HTTPS.

require.min.js download failed

**Comment by JexCheng** [comment]
Fixed. 
It is caused by Chrome Not allowed to navigate top frame to data URL：
https://stackoverflow.com/questions/45493234/jspdf-not-allowed-to-navigate-top-frame-to-data-url
